<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net48</TargetFramework><OutputType>WinExe</OutputType><UseWindowsForms>true</UseWindowsForms><IsPackable>false</IsPackable><AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects><GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType></PropertyGroup>
  <ItemGroup>
    <Reference Include="System.Net.Http" />
    <ProjectReference Include="../../src/Tansr.Sdk.Windows/Tansr.Sdk.Windows.csproj" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
    <Compile Include="../Shared/*.cs" Link="Shared/%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
