// <auto-generated>
// Generated by scripts/generate-api-routes.mjs from contract/api-manifest.json. Do not edit by hand.
// Manifest: tansr-api-manifest-v1 contract=unified-v1 revision=7
// Manifest schemaHash: b60e77ffcbf08d985a993dbdbd4cf610f12f7c7e70f090aee5ff8d523f70bb57
// Manifest file sha256: f6255bc868b4de5cb2af759a55069ab4651027d4125ef86d37f14a91d3307288 (85134 bytes)
// Source: tansr-cli packages/server/contract/api-manifest.json @ 64df76b24bfd3bc62850f4b04093553708b7708c
// </auto-generated>
#nullable enable
using System.Collections.Generic;

namespace Tansr.Sdk.Api;

public static partial class ApiRoutes
{
    /// <summary>Unified contract identifier carried by every <c>/api</c> response header <c>tansr-contract</c>.</summary>
    public const string Contract = "unified-v1";
    /// <summary>Revision of the vendored api-manifest; compared against <c>tansr-manifest-revision</c> when the caller asks for strict revision pinning.</summary>
    public const int ManifestRevision = 7;
    /// <summary>Operation-table hash published by the manifest (<c>schemaHash</c>).</summary>
    public const string ManifestSchemaHash = "b60e77ffcbf08d985a993dbdbd4cf610f12f7c7e70f090aee5ff8d523f70bb57";
    /// <summary>SHA-256 of the vendored <c>contract/api-manifest.json</c> bytes.</summary>
    public const string ManifestSha256 = "f6255bc868b4de5cb2af759a55069ab4651027d4125ef86d37f14a91d3307288";
    public const int OperationCount = 81;

    /// <summary><c>GET /api/manifest</c> (discovery).</summary>
    public static readonly ApiOperation DiscoveryManifest = new ApiOperation("discovery.manifest", "discovery", null, "GET", "/api/manifest", System.Array.Empty<string>(), System.Array.Empty<string>(), false, "read", null, null, null);
    /// <summary><c>GET /api/capabilities</c> (discovery).</summary>
    public static readonly ApiOperation DiscoveryCapabilities = new ApiOperation("discovery.capabilities", "discovery", null, "GET", "/api/capabilities", System.Array.Empty<string>(), System.Array.Empty<string>(), false, "read", null, null, null);
    /// <summary><c>GET /api/sessions/:id/capabilities</c> (discovery).</summary>
    public static readonly ApiOperation DiscoverySessionCapabilities = new ApiOperation("discovery.session.capabilities", "discovery", null, "GET", "/api/sessions/:id/capabilities", System.Array.Empty<string>(), System.Array.Empty<string>(), false, "read", null, null, null);
    /// <summary><c>GET /api/capabilities/sessions</c> (session, agent-session-v1).</summary>
    public static readonly ApiOperation SessionCapabilities = new ApiOperation("session.capabilities", "session", "agent-session-v1", "GET", "/api/capabilities/sessions", System.Array.Empty<string>(), new[] { "protocol" }, false, "read", null, null, null);
    /// <summary><c>POST /api/sessions</c> (session, agent-session-v1).</summary>
    public static readonly ApiOperation SessionCreate = new ApiOperation("session.create", "session", "agent-session-v1", "POST", "/api/sessions", System.Array.Empty<string>(), System.Array.Empty<string>(), false, "write", null, null, null);
    /// <summary><c>GET /api/sessions</c> (session, agent-session-v1).</summary>
    public static readonly ApiOperation SessionList = new ApiOperation("session.list", "session", "agent-session-v1", "GET", "/api/sessions", System.Array.Empty<string>(), new[] { "limit", "offset" }, false, "read", null, null, null);
    /// <summary><c>GET /api/sessions/:id</c> (session, agent-session-v1).</summary>
    public static readonly ApiOperation SessionGet = new ApiOperation("session.get", "session", "agent-session-v1", "GET", "/api/sessions/:id", System.Array.Empty<string>(), new[] { "include" }, false, "read", null, null, null);
    /// <summary><c>DELETE /api/sessions/:id</c> (session, agent-session-v1).</summary>
    public static readonly ApiOperation SessionClose = new ApiOperation("session.close", "session", "agent-session-v1", "DELETE", "/api/sessions/:id", System.Array.Empty<string>(), System.Array.Empty<string>(), false, "write", null, null, null);
    /// <summary><c>POST /api/sessions/:id/messages</c> (session, agent-session-v1).</summary>
    public static readonly ApiOperation SessionMessageSend = new ApiOperation("session.message.send", "session", "agent-session-v1", "POST", "/api/sessions/:id/messages", System.Array.Empty<string>(), System.Array.Empty<string>(), false, "write", null, null, null);
    /// <summary><c>GET /api/sessions/:id/events</c> (session, agent-session-v1).</summary>
    public static readonly ApiOperation SessionEventsObserve = new ApiOperation("session.events.observe", "session", "agent-session-v1", "GET", "/api/sessions/:id/events", System.Array.Empty<string>(), new[] { "exclude" }, true, "stream", null, null, null);
    /// <summary><c>POST /api/sessions/:id/interrupt</c> (session, agent-session-v1).</summary>
    public static readonly ApiOperation SessionInterrupt = new ApiOperation("session.interrupt", "session", "agent-session-v1", "POST", "/api/sessions/:id/interrupt", System.Array.Empty<string>(), System.Array.Empty<string>(), false, "write", null, null, null);
    /// <summary><c>GET /api/sessions/:id/history</c> (session, agent-session-v1).</summary>
    public static readonly ApiOperation SessionHistoryRead = new ApiOperation("session.history.read", "session", "agent-session-v1", "GET", "/api/sessions/:id/history", System.Array.Empty<string>(), new[] { "offset", "limit" }, false, "read", null, null, null);
    /// <summary><c>POST /api/sessions/:id/tool-results/:targetId</c> (session, agent-session-v1).</summary>
    public static readonly ApiOperation SessionToolResult = new ApiOperation("session.tool.result", "session", "agent-session-v1", "POST", "/api/sessions/:id/tool-results/:targetId", System.Array.Empty<string>(), System.Array.Empty<string>(), false, "write", null, null, null);
    /// <summary><c>POST /api/sessions/:id/permission/:ticketId</c> (session, agent-session-v1).</summary>
    public static readonly ApiOperation SessionPermissionDecide = new ApiOperation("session.permission.decide", "session", "agent-session-v1", "POST", "/api/sessions/:id/permission/:ticketId", System.Array.Empty<string>(), System.Array.Empty<string>(), false, "write", null, null, null);
    /// <summary><c>POST /api/sessions/:id/questions/:ticketId</c> (session, agent-session-v1).</summary>
    public static readonly ApiOperation SessionQuestionAnswer = new ApiOperation("session.question.answer", "session", "agent-session-v1", "POST", "/api/sessions/:id/questions/:ticketId", System.Array.Empty<string>(), System.Array.Empty<string>(), false, "write", null, null, null);
    /// <summary><c>POST /api/sessions/:id/compact</c> (session, agent-session-v1).</summary>
    public static readonly ApiOperation SessionCompact = new ApiOperation("session.compact", "session", "agent-session-v1", "POST", "/api/sessions/:id/compact", System.Array.Empty<string>(), System.Array.Empty<string>(), false, "write", null, null, null);
    /// <summary><c>GET /api/sessions/:id/checkpoints</c> (session, agent-session-v1).</summary>
    public static readonly ApiOperation SessionCheckpointList = new ApiOperation("session.checkpoint.list", "session", "agent-session-v1", "GET", "/api/sessions/:id/checkpoints", System.Array.Empty<string>(), System.Array.Empty<string>(), false, "read", null, null, null);
    /// <summary><c>POST /api/sessions/:id/checkpoints</c> (session, agent-session-v1).</summary>
    public static readonly ApiOperation SessionCheckpointCreate = new ApiOperation("session.checkpoint.create", "session", "agent-session-v1", "POST", "/api/sessions/:id/checkpoints", System.Array.Empty<string>(), System.Array.Empty<string>(), false, "write", null, null, null);
    /// <summary><c>POST /api/sessions/:id/checkpoints/import</c> (session, agent-session-v1).</summary>
    public static readonly ApiOperation SessionCheckpointImport = new ApiOperation("session.checkpoint.import", "session", "agent-session-v1", "POST", "/api/sessions/:id/checkpoints/import", System.Array.Empty<string>(), new[] { "label" }, false, "write", null, null, null);
    /// <summary><c>POST /api/sessions/:id/checkpoints/:targetId/restore</c> (session, agent-session-v1).</summary>
    public static readonly ApiOperation SessionCheckpointRestore = new ApiOperation("session.checkpoint.restore", "session", "agent-session-v1", "POST", "/api/sessions/:id/checkpoints/:targetId/restore", System.Array.Empty<string>(), System.Array.Empty<string>(), false, "write", null, null, null);
    /// <summary><c>GET /api/sessions/:id/checkpoints/:targetId/export</c> (session, agent-session-v1).</summary>
    public static readonly ApiOperation SessionCheckpointExport = new ApiOperation("session.checkpoint.export", "session", "agent-session-v1", "GET", "/api/sessions/:id/checkpoints/:targetId/export", System.Array.Empty<string>(), System.Array.Empty<string>(), false, "read", null, null, null);
    /// <summary><c>DELETE /api/sessions/:id/checkpoints/:targetId</c> (session, agent-session-v1).</summary>
    public static readonly ApiOperation SessionCheckpointDelete = new ApiOperation("session.checkpoint.delete", "session", "agent-session-v1", "DELETE", "/api/sessions/:id/checkpoints/:targetId", System.Array.Empty<string>(), System.Array.Empty<string>(), false, "write", null, null, null);
    /// <summary><c>POST /api/sessions/:id/cwd</c> (session, agent-session-v1).</summary>
    public static readonly ApiOperation SessionCwdSet = new ApiOperation("session.cwd.set", "session", "agent-session-v1", "POST", "/api/sessions/:id/cwd", System.Array.Empty<string>(), System.Array.Empty<string>(), false, "write", null, null, null);
    /// <summary><c>POST /api/sessions/:id/audio/transcriptions</c> (session, agent-session-v1).</summary>
    public static readonly ApiOperation SessionAudioTranscribe = new ApiOperation("session.audio.transcribe", "session", "agent-session-v1", "POST", "/api/sessions/:id/audio/transcriptions", System.Array.Empty<string>(), System.Array.Empty<string>(), false, "write", null, null, null);
    /// <summary><c>POST /api/sessions/:id/audio/speech</c> (session, agent-session-v1).</summary>
    public static readonly ApiOperation SessionAudioSpeak = new ApiOperation("session.audio.speak", "session", "agent-session-v1", "POST", "/api/sessions/:id/audio/speech", System.Array.Empty<string>(), System.Array.Empty<string>(), false, "write", null, null, null);
    /// <summary><c>GET /api/sessions/:id/input-capabilities</c> (session, agent-session-v1).</summary>
    public static readonly ApiOperation SessionInputCapabilities = new ApiOperation("session.input.capabilities", "session", "agent-session-v1", "GET", "/api/sessions/:id/input-capabilities", System.Array.Empty<string>(), System.Array.Empty<string>(), false, "read", null, null, null);
    /// <summary><c>POST /api/sessions/:id/inputs</c> (session, agent-session-v1).</summary>
    public static readonly ApiOperation SessionInputSubmit = new ApiOperation("session.input.submit", "session", "agent-session-v1", "POST", "/api/sessions/:id/inputs", System.Array.Empty<string>(), System.Array.Empty<string>(), false, "write", null, null, null);
    /// <summary><c>GET /api/sessions/:id/inputs/:targetId</c> (session, agent-session-v1).</summary>
    public static readonly ApiOperation SessionInputStatus = new ApiOperation("session.input.status", "session", "agent-session-v1", "GET", "/api/sessions/:id/inputs/:targetId", System.Array.Empty<string>(), new[] { "historyEpoch", "turnId" }, false, "read", null, null, null);
    /// <summary><c>POST /api/approvals/:id/credential</c> (session, agent-session-v1).</summary>
    public static readonly ApiOperation ApprovalCredentialSubmit = new ApiOperation("approval.credential.submit", "session", "agent-session-v1", "POST", "/api/approvals/:id/credential", System.Array.Empty<string>(), System.Array.Empty<string>(), false, "write", null, null, null);
    /// <summary><c>POST /api/sessions/:id/initialize</c> (execution, sdk2-ext-v1).</summary>
    public static readonly ApiOperation ExecutionInitialize = new ApiOperation("execution.initialize", "execution", "sdk2-ext-v1", "POST", "/api/sessions/:id/initialize", System.Array.Empty<string>(), System.Array.Empty<string>(), false, "write", null, null, null);
    /// <summary><c>GET /api/sessions/:id/execution-capabilities</c> (execution, sdk2-ext-v1).</summary>
    public static readonly ApiOperation ExecutionCapabilities = new ApiOperation("execution.capabilities", "execution", "sdk2-ext-v1", "GET", "/api/sessions/:id/execution-capabilities", System.Array.Empty<string>(), new[] { "protocol" }, false, "read", null, null, null);
    /// <summary><c>GET /api/sessions/:id/execution-boundary</c> (execution, sdk2-ext-v1).</summary>
    public static readonly ApiOperation ExecutionBoundary = new ApiOperation("execution.boundary", "execution", "sdk2-ext-v1", "GET", "/api/sessions/:id/execution-boundary", System.Array.Empty<string>(), new[] { "protocol" }, false, "read", null, null, null);
    /// <summary><c>POST /api/sessions/:id/execution-bindings</c> (execution, sdk2-ext-v1).</summary>
    public static readonly ApiOperation ExecutionBindingCreate = new ApiOperation("execution.binding.create", "execution", "sdk2-ext-v1", "POST", "/api/sessions/:id/execution-bindings", System.Array.Empty<string>(), System.Array.Empty<string>(), false, "write", null, null, null);
    /// <summary><c>GET /api/sessions/:id/executions/:targetId</c> (execution, sdk2-ext-v1).</summary>
    public static readonly ApiOperation ExecutionStatus = new ApiOperation("execution.status", "execution", "sdk2-ext-v1", "GET", "/api/sessions/:id/executions/:targetId", System.Array.Empty<string>(), new[] { "protocol" }, false, "read", null, null, null);
    /// <summary><c>POST /api/executors/connections</c> (execution, sdk2-ext-v1).</summary>
    public static readonly ApiOperation ExecutorRegister = new ApiOperation("executor.register", "execution", "sdk2-ext-v1", "POST", "/api/executors/connections", System.Array.Empty<string>(), System.Array.Empty<string>(), false, "write", null, null, null);
    /// <summary><c>POST /api/executors/:id/heartbeats</c> (execution, sdk2-ext-v1).</summary>
    public static readonly ApiOperation ExecutorHeartbeat = new ApiOperation("executor.heartbeat", "execution", "sdk2-ext-v1", "POST", "/api/executors/:id/heartbeats", System.Array.Empty<string>(), System.Array.Empty<string>(), false, "write", null, null, null);
    /// <summary><c>GET /api/executors/:id/operations</c> (execution, sdk2-ext-v1).</summary>
    public static readonly ApiOperation ExecutorOperationsPoll = new ApiOperation("executor.operations.poll", "execution", "sdk2-ext-v1", "GET", "/api/executors/:id/operations", System.Array.Empty<string>(), new[] { "protocol", "connectionId" }, false, "read", null, null, null);
    /// <summary><c>POST /api/executors/:id/receipts</c> (execution, sdk2-ext-v1).</summary>
    public static readonly ApiOperation ExecutorReceiptSubmit = new ApiOperation("executor.receipt.submit", "execution", "sdk2-ext-v1", "POST", "/api/executors/:id/receipts", System.Array.Empty<string>(), System.Array.Empty<string>(), false, "write", null, null, null);
    /// <summary><c>GET /api/capabilities/archive</c> (archive, sdk2-ext-v1).</summary>
    public static readonly ApiOperation ArchiveCapabilities = new ApiOperation("archive.capabilities", "archive", "sdk2-ext-v1", "GET", "/api/capabilities/archive", System.Array.Empty<string>(), System.Array.Empty<string>(), false, "read", null, null, null);
    /// <summary><c>GET /api/sessions/:id/binding-target</c> (archive, sdk2-ext-v1); versioned: ETag ← revision, If-Match → none.</summary>
    public static readonly ApiOperation ArchiveBindingTarget = new ApiOperation("archive.binding.target", "archive", "sdk2-ext-v1", "GET", "/api/sessions/:id/binding-target", System.Array.Empty<string>(), new[] { "protocol" }, false, "read", new[] { "revision" }, null, null);
    /// <summary><c>POST /api/archive/bindings</c> (archive, sdk2-ext-v1); versioned: ETag ← revision, If-Match → expectedRevision (sequence).</summary>
    public static readonly ApiOperation ArchiveBindingCreate = new ApiOperation("archive.binding.create", "archive", "sdk2-ext-v1", "POST", "/api/archive/bindings", System.Array.Empty<string>(), System.Array.Empty<string>(), false, "write", new[] { "revision" }, new[] { "expectedRevision" }, "sequence");
    /// <summary><c>GET /api/archive/bindings/:id</c> (archive, sdk2-ext-v1); versioned: ETag ← revision, If-Match → none.</summary>
    public static readonly ApiOperation ArchiveBindingGet = new ApiOperation("archive.binding.get", "archive", "sdk2-ext-v1", "GET", "/api/archive/bindings/:id", System.Array.Empty<string>(), new[] { "protocol" }, false, "read", new[] { "revision" }, null, null);
    /// <summary><c>POST /api/archive/bindings/:id/close</c> (archive, sdk2-ext-v1); versioned: ETag ← revision, If-Match → expectedRevision (sequence).</summary>
    public static readonly ApiOperation ArchiveBindingClose = new ApiOperation("archive.binding.close", "archive", "sdk2-ext-v1", "POST", "/api/archive/bindings/:id/close", System.Array.Empty<string>(), System.Array.Empty<string>(), false, "write", new[] { "revision" }, new[] { "expectedRevision" }, "sequence");
    /// <summary><c>GET /api/archive/bindings/:id/archive/status</c> (archive, sdk2-ext-v1); versioned: ETag ← revision, If-Match → none.</summary>
    public static readonly ApiOperation ArchiveStatus = new ApiOperation("archive.status", "archive", "sdk2-ext-v1", "GET", "/api/archive/bindings/:id/archive/status", System.Array.Empty<string>(), new[] { "protocol" }, false, "read", new[] { "revision" }, null, null);
    /// <summary><c>GET /api/archive/bindings/:id/events</c> (archive, sdk2-ext-v1).</summary>
    public static readonly ApiOperation ArchiveEventsObserve = new ApiOperation("archive.events.observe", "archive", "sdk2-ext-v1", "GET", "/api/archive/bindings/:id/events", System.Array.Empty<string>(), new[] { "protocol" }, true, "stream", null, null, null);
    /// <summary><c>GET /api/archive/bindings/:id/archive/records</c> (archive, sdk2-ext-v1).</summary>
    public static readonly ApiOperation ArchiveRecordsRead = new ApiOperation("archive.records.read", "archive", "sdk2-ext-v1", "GET", "/api/archive/bindings/:id/archive/records", System.Array.Empty<string>(), new[] { "protocol", "historyEpoch", "deletionGeneration", "projectionRevision", "limit", "maxBytes", "afterSequence" }, false, "read", null, null, null);
    /// <summary><c>GET /api/archive/bindings/:id/archive/artifacts/:targetId</c> (archive, sdk2-ext-v1).</summary>
    public static readonly ApiOperation ArchiveArtifactRead = new ApiOperation("archive.artifact.read", "archive", "sdk2-ext-v1", "GET", "/api/archive/bindings/:id/archive/artifacts/:targetId", System.Array.Empty<string>(), new[] { "protocol", "historyEpoch", "deletionGeneration", "projectionRevision", "offset", "maxBytes" }, false, "read", null, null, null);
    /// <summary><c>POST /api/archive/bindings/:id/archive/acks</c> (archive, sdk2-ext-v1); versioned: ETag ← revision, If-Match → expectedRevision (sequence).</summary>
    public static readonly ApiOperation ArchiveAckCommit = new ApiOperation("archive.ack.commit", "archive", "sdk2-ext-v1", "POST", "/api/archive/bindings/:id/archive/acks", System.Array.Empty<string>(), System.Array.Empty<string>(), false, "write", new[] { "revision" }, new[] { "expectedRevision" }, "sequence");
    /// <summary><c>POST /api/archive/bindings/:id/archive/ack-rebases</c> (archive, sdk2-archive-recovery-v1).</summary>
    public static readonly ApiOperation ArchiveAckRebase = new ApiOperation("archive.ack.rebase", "archive", "sdk2-archive-recovery-v1", "POST", "/api/archive/bindings/:id/archive/ack-rebases", System.Array.Empty<string>(), System.Array.Empty<string>(), false, "write", null, null, null);
    /// <summary><c>GET /api/archive/operations</c> (archive, sdk2-ext-v1).</summary>
    public static readonly ApiOperation ArchiveOperationQuery = new ApiOperation("archive.operation.query", "archive", "sdk2-ext-v1", "GET", "/api/archive/operations", System.Array.Empty<string>(), new[] { "protocol", "operation", "operationEpoch", "requestId", "bindingId", "sessionId" }, false, "read", null, null, null);
    /// <summary><c>POST /api/archive/sync/:id</c> (archive-sync, archive-sync-v1).</summary>
    public static readonly ApiOperation ArchiveSync = new ApiOperation("archive.sync", "archive-sync", "archive-sync-v1", "POST", "/api/archive/sync/:id", System.Array.Empty<string>(), System.Array.Empty<string>(), false, "write", null, null, null);
    /// <summary><c>POST /api/archive/bindings/:id/material-responses</c> (archive, sdk2-ext-v1).</summary>
    public static readonly ApiOperation MaterialResponseSubmit = new ApiOperation("material.response.submit", "archive", "sdk2-ext-v1", "POST", "/api/archive/bindings/:id/material-responses", System.Array.Empty<string>(), System.Array.Empty<string>(), false, "write", null, null, null);
    /// <summary><c>GET /api/archive/bindings/:id/materials/:targetId</c> (archive, sdk2-ext-v1).</summary>
    public static readonly ApiOperation MaterialStatus = new ApiOperation("material.status", "archive", "sdk2-ext-v1", "GET", "/api/archive/bindings/:id/materials/:targetId", System.Array.Empty<string>(), new[] { "protocol" }, false, "read", null, null, null);
    /// <summary><c>GET /api/archive/bindings/:id/materials/:targetId/uploads/:uploadId</c> (archive, sdk2-ext-v1).</summary>
    public static readonly ApiOperation MaterialUploadStatus = new ApiOperation("material.upload.status", "archive", "sdk2-ext-v1", "GET", "/api/archive/bindings/:id/materials/:targetId/uploads/:uploadId", System.Array.Empty<string>(), new[] { "protocol" }, false, "read", null, null, null);
    /// <summary><c>POST /api/archive/bindings/:id/materials/:targetId/uploads/:uploadId/chunks</c> (archive, sdk2-ext-v1).</summary>
    public static readonly ApiOperation MaterialUploadChunk = new ApiOperation("material.upload.chunk", "archive", "sdk2-ext-v1", "POST", "/api/archive/bindings/:id/materials/:targetId/uploads/:uploadId/chunks", System.Array.Empty<string>(), System.Array.Empty<string>(), false, "write", null, null, null);
    /// <summary><c>GET /api/capabilities/cache</c> (cache, sdk2-cache-v1).</summary>
    public static readonly ApiOperation CacheCapabilities = new ApiOperation("cache.capabilities", "cache", "sdk2-cache-v1", "GET", "/api/capabilities/cache", System.Array.Empty<string>(), System.Array.Empty<string>(), false, "read", null, null, null);
    /// <summary><c>POST /api/cache/bindings</c> (cache, sdk2-cache-v1); versioned: ETag ← binding.revision, If-Match → none.</summary>
    public static readonly ApiOperation CacheBindingOpen = new ApiOperation("cache.binding.open", "cache", "sdk2-cache-v1", "POST", "/api/cache/bindings", System.Array.Empty<string>(), System.Array.Empty<string>(), false, "write", new[] { "binding", "revision" }, null, null);
    /// <summary><c>GET /api/cache/bindings/:id</c> (cache, sdk2-cache-v1); versioned: ETag ← revision, If-Match → none.</summary>
    public static readonly ApiOperation CacheBindingGet = new ApiOperation("cache.binding.get", "cache", "sdk2-cache-v1", "GET", "/api/cache/bindings/:id", System.Array.Empty<string>(), new[] { "protocol" }, false, "read", new[] { "revision" }, null, null);
    /// <summary><c>POST /api/cache/bindings/:id/renew</c> (cache, sdk2-cache-v1); versioned: ETag ← binding.revision, If-Match → expectedRevision (sequence).</summary>
    public static readonly ApiOperation CacheBindingRenew = new ApiOperation("cache.binding.renew", "cache", "sdk2-cache-v1", "POST", "/api/cache/bindings/:id/renew", System.Array.Empty<string>(), System.Array.Empty<string>(), false, "write", new[] { "binding", "revision" }, new[] { "expectedRevision" }, "sequence");
    /// <summary><c>POST /api/cache/bindings/:id/rebind</c> (cache, sdk2-cache-v1); versioned: ETag ← binding.revision, If-Match → expectedRevision (sequence).</summary>
    public static readonly ApiOperation CacheBindingRebind = new ApiOperation("cache.binding.rebind", "cache", "sdk2-cache-v1", "POST", "/api/cache/bindings/:id/rebind", System.Array.Empty<string>(), System.Array.Empty<string>(), false, "write", new[] { "binding", "revision" }, new[] { "expectedRevision" }, "sequence");
    /// <summary><c>POST /api/cache/bindings/:id/rotate</c> (cache, sdk2-cache-v1); versioned: ETag ← binding.revision, If-Match → expectedRevision (sequence).</summary>
    public static readonly ApiOperation CacheBindingRotate = new ApiOperation("cache.binding.rotate", "cache", "sdk2-cache-v1", "POST", "/api/cache/bindings/:id/rotate", System.Array.Empty<string>(), System.Array.Empty<string>(), false, "write", new[] { "binding", "revision" }, new[] { "expectedRevision" }, "sequence");
    /// <summary><c>POST /api/cache/bindings/:id/close</c> (cache, sdk2-cache-v1); versioned: ETag ← binding.revision, If-Match → expectedRevision (sequence).</summary>
    public static readonly ApiOperation CacheBindingClose = new ApiOperation("cache.binding.close", "cache", "sdk2-cache-v1", "POST", "/api/cache/bindings/:id/close", System.Array.Empty<string>(), System.Array.Empty<string>(), false, "write", new[] { "binding", "revision" }, new[] { "expectedRevision" }, "sequence");
    /// <summary><c>GET /api/cache/operations</c> (cache, sdk2-cache-v1).</summary>
    public static readonly ApiOperation CacheOperationQuery = new ApiOperation("cache.operation.query", "cache", "sdk2-cache-v1", "GET", "/api/cache/operations", System.Array.Empty<string>(), new[] { "protocol", "operation", "operationEpoch", "requestId", "bindingId" }, false, "read", null, null, null);
    /// <summary><c>GET /api/cache/bindings/:id/diagnostics</c> (cache, sdk2-cache-v1).</summary>
    public static readonly ApiOperation CacheDiagnostics = new ApiOperation("cache.diagnostics", "cache", "sdk2-cache-v1", "GET", "/api/cache/bindings/:id/diagnostics", System.Array.Empty<string>(), new[] { "protocol", "after", "limit" }, false, "read", null, null, null);
    /// <summary><c>GET /api/cache/core/v1/bindings/:id/diagnostics</c> (cache, sdk2-cache-core-v1).</summary>
    public static readonly ApiOperation CacheCoreDiagnostics = new ApiOperation("cache.core.diagnostics", "cache", "sdk2-cache-core-v1", "GET", "/api/cache/core/v1/bindings/:id/diagnostics", System.Array.Empty<string>(), new[] { "protocol", "limit", "after" }, false, "read", null, null, null);
    /// <summary><c>GET /api/capabilities/terminal</c> (terminal, terminal-services-v1).</summary>
    public static readonly ApiOperation TerminalCapabilities = new ApiOperation("terminal.capabilities", "terminal", "terminal-services-v1", "GET", "/api/capabilities/terminal", System.Array.Empty<string>(), new[] { "contract" }, false, "read", null, null, null);
    /// <summary><c>POST /api/terminal/bindings</c> (terminal, terminal-services-v1).</summary>
    public static readonly ApiOperation TerminalBindingCreate = new ApiOperation("terminal.binding.create", "terminal", "terminal-services-v1", "POST", "/api/terminal/bindings", System.Array.Empty<string>(), System.Array.Empty<string>(), false, "write", null, null, null);
    /// <summary><c>GET /api/terminal/executors/:id/events</c> (terminal, terminal-services-v1).</summary>
    public static readonly ApiOperation TerminalExecutorEventsObserve = new ApiOperation("terminal.executor.events.observe", "terminal", "terminal-services-v1", "GET", "/api/terminal/executors/:id/events", System.Array.Empty<string>(), new[] { "contract", "sessionContract", "connectionId" }, true, "stream", null, null, null);
    /// <summary><c>POST /api/terminal/executors/:id/output-batches</c> (terminal, terminal-services-v1).</summary>
    public static readonly ApiOperation TerminalOutputBatch = new ApiOperation("terminal.output.batch", "terminal", "terminal-services-v1", "POST", "/api/terminal/executors/:id/output-batches", System.Array.Empty<string>(), System.Array.Empty<string>(), false, "write", null, null, null);
    /// <summary><c>GET /api/terminal/executors/:id/operations/:targetId</c> (terminal, terminal-services-v1).</summary>
    public static readonly ApiOperation TerminalExecutionState = new ApiOperation("terminal.execution.state", "terminal", "terminal-services-v1", "GET", "/api/terminal/executors/:id/operations/:targetId", System.Array.Empty<string>(), new[] { "contract", "sessionContract", "sessionId", "requestDigest", "connectionId" }, false, "read", null, null, null);
    /// <summary><c>GET /api/terminal/sessions/:id/tool-output</c> (terminal, terminal-services-v1).</summary>
    public static readonly ApiOperation TerminalOutputObserve = new ApiOperation("terminal.output.observe", "terminal", "terminal-services-v1", "GET", "/api/terminal/sessions/:id/tool-output", System.Array.Empty<string>(), new[] { "contract", "sessionContract", "operationId", "requestDigest", "afterSeq" }, true, "stream", null, null, null);
    /// <summary><c>GET /api/terminal/sessions/:id/tool-output-status</c> (terminal, terminal-services-v1).</summary>
    public static readonly ApiOperation TerminalOutputStatus = new ApiOperation("terminal.output.status", "terminal", "terminal-services-v1", "GET", "/api/terminal/sessions/:id/tool-output-status", System.Array.Empty<string>(), new[] { "contract", "sessionContract", "operationId", "requestDigest" }, false, "read", null, null, null);
    /// <summary><c>GET /api/terminal/sessions/:id/configuration</c> (terminal, terminal-services-v1); versioned: ETag ← configuration.revision, If-Match → none.</summary>
    public static readonly ApiOperation TerminalConfigurationRead = new ApiOperation("terminal.configuration.read", "terminal", "terminal-services-v1", "GET", "/api/terminal/sessions/:id/configuration", new[] { "/api/sessions/:id/configuration" }, new[] { "contract", "sessionContract" }, false, "read", new[] { "configuration", "revision" }, null, null);
    /// <summary><c>POST /api/terminal/sessions/:id/configuration</c> (terminal, terminal-services-v1); versioned: ETag ← configuration.revision, If-Match → expectedRevision (integer).</summary>
    public static readonly ApiOperation TerminalConfigurationCommit = new ApiOperation("terminal.configuration.commit", "terminal", "terminal-services-v1", "POST", "/api/terminal/sessions/:id/configuration", new[] { "/api/sessions/:id/configuration" }, System.Array.Empty<string>(), false, "write", new[] { "configuration", "revision" }, new[] { "expectedRevision" }, "integer");
    /// <summary><c>GET /api/terminal/sessions/:id/memory</c> (terminal, terminal-services-v1); versioned: ETag ← memory.revision, If-Match → none.</summary>
    public static readonly ApiOperation TerminalMemoryRead = new ApiOperation("terminal.memory.read", "terminal", "terminal-services-v1", "GET", "/api/terminal/sessions/:id/memory", new[] { "/api/sessions/:id/memory" }, new[] { "contract", "sessionContract" }, false, "read", new[] { "memory", "revision" }, null, null);
    /// <summary><c>POST /api/terminal/sessions/:id/memory/commands</c> (terminal, terminal-services-v1); versioned: ETag ← none, If-Match → expectedRevision (sequence).</summary>
    public static readonly ApiOperation TerminalMemoryCommand = new ApiOperation("terminal.memory.command", "terminal", "terminal-services-v1", "POST", "/api/terminal/sessions/:id/memory/commands", new[] { "/api/sessions/:id/memory/commands" }, System.Array.Empty<string>(), false, "write", null, new[] { "expectedRevision" }, "sequence");
    /// <summary><c>GET /api/terminal/sessions/:id/memory/commands/:targetId</c> (terminal, terminal-services-v1).</summary>
    public static readonly ApiOperation TerminalMemoryReceipt = new ApiOperation("terminal.memory.receipt", "terminal", "terminal-services-v1", "GET", "/api/terminal/sessions/:id/memory/commands/:targetId", new[] { "/api/sessions/:id/memory/commands/:targetId" }, new[] { "contract", "sessionContract", "requestId" }, false, "read", null, null, null);
    /// <summary><c>GET /api/terminal/observation/sessions/:id/resources</c> (terminal-observation, terminal-observation-v1).</summary>
    public static readonly ApiOperation TerminalObservationResources = new ApiOperation("terminal.observation.resources", "terminal-observation", "terminal-observation-v1", "GET", "/api/terminal/observation/sessions/:id/resources", System.Array.Empty<string>(), new[] { "contract", "sessionContract" }, false, "read", null, null, null);
    /// <summary><c>GET /api/terminal/observation/sessions/:id/output-correlations</c> (terminal-observation, terminal-observation-v1).</summary>
    public static readonly ApiOperation TerminalObservationCorrelations = new ApiOperation("terminal.observation.correlations", "terminal-observation", "terminal-observation-v1", "GET", "/api/terminal/observation/sessions/:id/output-correlations", System.Array.Empty<string>(), new[] { "contract", "sessionContract", "toolCallId" }, false, "read", null, null, null);
    /// <summary><c>GET /api/terminal/profile/sessions/:id/catalog</c> (terminal-profile, terminal-profile-v1).</summary>
    public static readonly ApiOperation TerminalProfileCatalog = new ApiOperation("terminal.profile.catalog", "terminal-profile", "terminal-profile-v1", "GET", "/api/terminal/profile/sessions/:id/catalog", System.Array.Empty<string>(), new[] { "contract", "sessionContract" }, false, "read", null, null, null);
    /// <summary><c>GET /api/terminal/profile/sessions/:id/usage</c> (terminal-profile, terminal-profile-v1).</summary>
    public static readonly ApiOperation TerminalProfileUsage = new ApiOperation("terminal.profile.usage", "terminal-profile", "terminal-profile-v1", "GET", "/api/terminal/profile/sessions/:id/usage", System.Array.Empty<string>(), new[] { "contract", "sessionContract" }, false, "read", null, null, null);

    /// <summary>All operations in manifest order.</summary>
    public static readonly IReadOnlyList<ApiOperation> All = new ApiOperation[]
    {
        DiscoveryManifest,
        DiscoveryCapabilities,
        DiscoverySessionCapabilities,
        SessionCapabilities,
        SessionCreate,
        SessionList,
        SessionGet,
        SessionClose,
        SessionMessageSend,
        SessionEventsObserve,
        SessionInterrupt,
        SessionHistoryRead,
        SessionToolResult,
        SessionPermissionDecide,
        SessionQuestionAnswer,
        SessionCompact,
        SessionCheckpointList,
        SessionCheckpointCreate,
        SessionCheckpointImport,
        SessionCheckpointRestore,
        SessionCheckpointExport,
        SessionCheckpointDelete,
        SessionCwdSet,
        SessionAudioTranscribe,
        SessionAudioSpeak,
        SessionInputCapabilities,
        SessionInputSubmit,
        SessionInputStatus,
        ApprovalCredentialSubmit,
        ExecutionInitialize,
        ExecutionCapabilities,
        ExecutionBoundary,
        ExecutionBindingCreate,
        ExecutionStatus,
        ExecutorRegister,
        ExecutorHeartbeat,
        ExecutorOperationsPoll,
        ExecutorReceiptSubmit,
        ArchiveCapabilities,
        ArchiveBindingTarget,
        ArchiveBindingCreate,
        ArchiveBindingGet,
        ArchiveBindingClose,
        ArchiveStatus,
        ArchiveEventsObserve,
        ArchiveRecordsRead,
        ArchiveArtifactRead,
        ArchiveAckCommit,
        ArchiveAckRebase,
        ArchiveOperationQuery,
        ArchiveSync,
        MaterialResponseSubmit,
        MaterialStatus,
        MaterialUploadStatus,
        MaterialUploadChunk,
        CacheCapabilities,
        CacheBindingOpen,
        CacheBindingGet,
        CacheBindingRenew,
        CacheBindingRebind,
        CacheBindingRotate,
        CacheBindingClose,
        CacheOperationQuery,
        CacheDiagnostics,
        CacheCoreDiagnostics,
        TerminalCapabilities,
        TerminalBindingCreate,
        TerminalExecutorEventsObserve,
        TerminalOutputBatch,
        TerminalExecutionState,
        TerminalOutputObserve,
        TerminalOutputStatus,
        TerminalConfigurationRead,
        TerminalConfigurationCommit,
        TerminalMemoryRead,
        TerminalMemoryCommand,
        TerminalMemoryReceipt,
        TerminalObservationResources,
        TerminalObservationCorrelations,
        TerminalProfileCatalog,
        TerminalProfileUsage,
    };

    /// <summary>Domain vocabulary (unified-v1 schema Domain enum; discovery is facade-owned).</summary>
    public static readonly IReadOnlyList<string> Domains = new[] { "discovery", "session", "execution", "archive", "archive-sync", "cache", "terminal", "terminal-observation", "terminal-profile" };

    /// <summary>Family schema fingerprints as published by the manifest (<c>families[].sha256</c>).</summary>
    public static class Families
    {
        /// <summary>agent-session-v1: frozen, source packages/server/src/v2/contract.ts (domains session).</summary>
        public const string AgentSessionV1 = "6e1876edc476322e2fc3613958f5b44700bb80ea23550fa794f5729220674f3e";
        /// <summary>sdk2-ext-v1: final, source doc/rfc/sdk2-ext-v1.schema.json (domains archive, execution).</summary>
        public const string Sdk2ExtV1 = "969273844ca9196f19dd71b292b65a49307d63be0d20a0caf557e105ba6d8605";
        /// <summary>sdk2-archive-recovery-v1: additive, source doc/rfc/sdk2-archive-recovery-v1.schema.json (domains archive).</summary>
        public const string Sdk2ArchiveRecoveryV1 = "f530de1096b4f5d56ea688b7f2cec9ae66deb7d3719db85ab1f48287d3bd7ad4";
        /// <summary>archive-sync-v1: additive, source doc/rfc/archive-sync-v1.schema.json (domains archive-sync).</summary>
        public const string ArchiveSyncV1 = "7468fb72c80ce8d0bbe298219c894578020f249d7532c63cad91e8dad4a412bb";
        /// <summary>sdk2-cache-v1: drafted, source doc/rfc/sdk2-cache-v1.schema.json (domains cache).</summary>
        public const string Sdk2CacheV1 = "88e7941861fab1a6380b9226e3a42adb8c872efdf720dc36e92ffa42da43d818";
        /// <summary>sdk2-cache-core-v1: additive, source doc/rfc/sdk2-cache-core-v1.schema.json (domains cache).</summary>
        public const string Sdk2CacheCoreV1 = "5b052117919f3ef751310a36db3a2c1dac96daeda2f10a4bb78028edc0d5cbff";
        /// <summary>terminal-services-v1: candidate, source doc/rfc/terminal-services-v1.schema.json (domains terminal).</summary>
        public const string TerminalServicesV1 = "8cd8c7c55a84c5700373aed75d5653a0737d718bfe0546641be367bda1a11896";
        /// <summary>terminal-observation-v1: additive, source doc/rfc/terminal-observation-v1.schema.json (domains terminal-observation).</summary>
        public const string TerminalObservationV1 = "b6668463458e78b2cfe23baa72d9d9ac6263a248467dd8aeb60387fc2f67c28a";
        /// <summary>terminal-profile-v1: additive, source doc/rfc/terminal-profile-v1.schema.json (domains terminal-profile).</summary>
        public const string TerminalProfileV1 = "560ad136f0619a2a0592151d56e10871c3799ca438163c4e2872381bf5f5159a";
        /// <summary>terminal-shell-sandbox-v1: additive, source doc/rfc/terminal-shell-sandbox-v1.schema.json (domains terminal).</summary>
        public const string TerminalShellSandboxV1 = "be3ebcf6dc650844319a18a15f6abbefb9316f704410b591f9ba6dcab7620fe1";
        /// <summary>unified-v1: candidate, source doc/rfc/unified-v1.schema.json (domains discovery).</summary>
        public const string UnifiedV1 = "fd07962916f7662ecc69c3f8c8d2b79aa5b99f542cbfd310a50f56777e51f117";
    }

    /// <summary>Body key path the facade fills from <c>Idempotency-Key</c> for a family (<c>families[].requestIdPath</c>, revision 7),
    /// or null when the family body has no such position or the family is unknown.</summary>
    public static IReadOnlyList<string>? FamilyRequestIdPath(string family) => family switch
    {
        "sdk2-ext-v1" => new[] { "request", "requestId" },
        "sdk2-archive-recovery-v1" => new[] { "request", "requestId" },
        "sdk2-cache-v1" => new[] { "request", "requestId" },
        "sdk2-cache-core-v1" => new[] { "request", "requestId" },
        "terminal-services-v1" => new[] { "requestId" },
        "terminal-observation-v1" => new[] { "requestId" },
        "terminal-profile-v1" => new[] { "requestId" },
        _ => null,
    };

    /// <summary>Primary family for a domain (first manifest family declaring it), or null for unknown domains.</summary>
    public static string? DomainFamily(string domain) => domain switch
    {
        "session" => "agent-session-v1",
        "archive" => "sdk2-ext-v1",
        "execution" => "sdk2-ext-v1",
        "archive-sync" => "archive-sync-v1",
        "cache" => "sdk2-cache-v1",
        "terminal" => "terminal-services-v1",
        "terminal-observation" => "terminal-observation-v1",
        "terminal-profile" => "terminal-profile-v1",
        "discovery" => "unified-v1",
        _ => null,
    };

    /// <summary>Expected <c>tansr-schema-hash</c> value for a domain, or null when the domain is unknown. <c>discovery</c> is the
    /// manifest aggregate <see cref="ManifestSchemaHash"/>; other domains carry their primary family source SHA (手册 §16.4).</summary>
    public static string? DomainSchemaHash(string domain) => domain switch
    {
        "session" => "sha256:6e1876edc476322e2fc3613958f5b44700bb80ea23550fa794f5729220674f3e",
        "archive" => "sha256:969273844ca9196f19dd71b292b65a49307d63be0d20a0caf557e105ba6d8605",
        "execution" => "sha256:969273844ca9196f19dd71b292b65a49307d63be0d20a0caf557e105ba6d8605",
        "archive-sync" => "sha256:7468fb72c80ce8d0bbe298219c894578020f249d7532c63cad91e8dad4a412bb",
        "cache" => "sha256:88e7941861fab1a6380b9226e3a42adb8c872efdf720dc36e92ffa42da43d818",
        "terminal" => "sha256:8cd8c7c55a84c5700373aed75d5653a0737d718bfe0546641be367bda1a11896",
        "terminal-observation" => "sha256:b6668463458e78b2cfe23baa72d9d9ac6263a248467dd8aeb60387fc2f67c28a",
        "terminal-profile" => "sha256:560ad136f0619a2a0592151d56e10871c3799ca438163c4e2872381bf5f5159a",
        "discovery" => "sha256:" + ManifestSchemaHash,
        _ => null,
    };
}
